### PR TITLE
Vapor Console Support

### PR DESCRIPTION
**Pull request by shnhrrsn**
Rewrote installer ontop of Vapor Console [#2]

TODO:
- [ ] Make project buildable via Xcode (unsure how to include vapor/vapor-console)
- [ ] Update bundled binary

### CODE REVIEW

**Comment by mpclarkson** [comment]
@shnhrrsn - I can't build this in either `debug` or `release`, I get the following error:

```
ld: framework not found XCTest for architecture x86_64
``

**Comment by shnhrrsn** [comment]
It's due to a bug in the latest swiftpm, Vapor/Tests needs to be deleted/renamed: https://github.com/qutheory/vapor-example/blob/master/run

**Comment by mpclarkson** [comment]
Ok, thanks

**Comment by mpclarkson** [comment]
I have this building now but do you think we should simply call it `vapor` rather than `VaporInstaller`?

It seems more intuitive to run `vapor new project` rather than `VaporInstaller new project`. This is how rails and laravel do it.

**Comment by shnhrrsn** [comment]
For installation it should definitely be just "vapor" (see: #6), but I don't think we can actually call the target Vapor when building due it having the Vapor framework as a target.

**Pull request merged**
